--DROP TYPE QUT_SUPPLIER_FULL_OBJ;
--DROP TYPE QUT_SUPP_SITES_ALL_TAB;
--DROP TYPE QUT_SUPP_SITES_ALL_OBJ;

-- site
CREATE OR REPLACE TYPE QUT_SUPP_SITES_ALL_OBJ FORCE AS OBJECT
(
SUPPLIER_ID		        NUMBER,
SUPPLIER_SITE_ID        NUMBER,
SUPPLIER_SITE_NAME		VARCHAR2 (15),
SITE_ADDRESS_LINE_1		VARCHAR2 (240),
SITE_ADDRESS_LINE_2		VARCHAR2 (240),
SITE_ADDRESS_LINE_3		VARCHAR2 (240),
SITE_ADDRESS_LINE_4		VARCHAR2 (240),
SITE_CITY	            VARCHAR2 (60),
SITE_STATE	            VARCHAR2 (150),
SITE_POSTCODE	        VARCHAR2 (60),
SITE_COUNTRY	        VARCHAR2 (60),
SITE_AREA_CODE          VARCHAR2 (10),
SITE_PHONE              VARCHAR2 (15),
SITE_EMAIL_ADDRESS	    VARCHAR2 (2000),
SITE_REMITTANCE_ADDRESS	VARCHAR2 (2000),
SITE_INACTIVE_DATE	    DATE,
CREATION_DATE           DATE,
CREATED_BY              NUMBER,
LAST_UPDATE_DATE        DATE,
LAST_UPDATE_BY          NUMBER,
BANKACC_EXIST_IND       VARCHAR2 (1)
);
/

CREATE OR REPLACE TYPE QUT_SUPP_SITES_ALL_TAB FORCE AS TABLE OF QUT_SUPP_SITES_ALL_OBJ;
/


-- supplier
CREATE OR REPLACE TYPE QUT_SUPPLIER_FULL_OBJ FORCE AS OBJECT
(
SUPPLIER_ID		        NUMBER,
SUPPLIER_NUM	        VARCHAR2 (30),
SUPPLIER_NAME	        VARCHAR2 (240),
SUPPLIER_TYPE	        VARCHAR2 (30),
SUPPLIER_ABN		    VARCHAR2 (20),
SUPPLIER_CONFIDENTIAL	VARCHAR2 (150),
SUPPLIER_INACTIVE_DATE	DATE,
SUPPLIER_EMPLOYEE_ID    NUMBER,
SUPPLIER_STUDENT_NUMBER VARCHAR2 (20),
CREATION_DATE           DATE,
CREATED_BY              NUMBER,
LAST_UPDATE_DATE        DATE,
LAST_UPDATE_BY          NUMBER,
RECEIPT_REQUIRED        VARCHAR2 (1),
SUPPLIER_SITE           QUT_SUPP_SITES_ALL_TAB
);
/

